### ISSUE TITLE
Require the user to provide an Agent Access Token

### ISSUE THREAD

**Issue by alannix-lw** [lacework/terraform-aws-ssm-agent#26]
Would it make sense to require an agent access token, rather than defaulting to nothing?

https://github.com/lacework/terraform-aws-ssm-agent/blob/a723c2b63f7e1aba6d7af67903e69487d656bf9a/variables.tf#L10

**Comment by afiune** [comment]
I don't think it is a requirement since this module only configures a SSM document which can be run from the AWS console and there you can pass the token as a variable. 

Only it is a requirement￼￼￼ if you make an association so that The document is executed on the fleet of instances, this is covered in our examples I believe.

@JPLachance thoughts?

**Comment by JPLachance** [comment]
Greetings,

We have a TODO in the code: https://github.com/lacework/terraform-aws-ssm-agent/blob/main/setup_lacework_agent.sh#L10

The end goal is to make the SSM Document fetch the agent token from a secured secrets store at runtime instead of letting it visible inside the AWS Console.

Also, in some environments, we might have multiple agent tokens. Since the association is the one passing the token to the document, we can share one Document with multiple associations.

This is why, at the moment, the token is not mandatory. Making it mandatory would go against the plan of using a secrets store and would break the ability to have one Document used for multiple agent tokens.

Does that make sens?

**Comment by alannix-lw** [comment]
Hey @JPLachance - that makes perfect sense.  However, we had an issue this week where a prospect forgot to provide the access token, so agents were deployed with an empty token.  We'd like to provide some more direct feedback to the user in that situation.

Based on your comments, it sounds like we would want to build some logic into the `setup_lacework_agent.sh` to provide an error message and exit if the token is empty.

Do you concur / do you see any potential issues with that?  If that sounds good, I can work on a simple PR.

**Comment by JPLachance** [comment]
It sounds like a good option to me yes!
